name: CVD Multi-Task Optimization Tests
'on':
  - push
  - workflow_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: CVD Multi-Task Optimization Test
        id: cvd-mtbo-test
        uses: classroom-resources/autograding-python-grader@v1
        with:
          timeout: 600
          max-score: 10
          setup-command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          test-command: pytest MTBO_assignment_test.py -v
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          CVD_MTBO_TEST_RESULTS: "${{steps.cvd-mtbo-test.outputs.result}}"
        with:
          runners: cvd-mtbo-test
